version: 2

builds:
    - main: ./cmd/cli
      ldflags:
          - -s -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{.Date}}'
      env:
          - CGO_ENABLED=0
          - GOPRIVATE=github.com/catalogfi/*
      goos:
          - linux
          - darwin
          - windows
      goarch:
          - amd64
          - arm64

checksum:
    name_template: "checksums.txt"

snapshot:
    name_template: "{{ .Tag }}-next"

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"

release:
    prerelease: auto
