db_url = "postgres://postgres:postgres@localhost:5432/garden"
quote_url = "http://quote:6969"
bitcoin_indexer_url = "http://electrs:30000"
jwt_secret = "my_secret"
api_key_v1_signer = "0xC63F0632E640580eF3C3F2290767b920C6a36b8d"
integrator_manager_url = "http://integrator-api:5444"
assets_url = "http://local-cdn:80/local_assets.json"
rpc_url = "http://rpc.localhost"
starknet_relay_url = "http://starknet-relayer:4436"
solana_relay_url = "http://solana-relayer:5014"