services:
  # RPC daemon
  bitcoin:
    image: lncm/bitcoind:v24.0.1
    container_name: bitcoin
    # wildcard user 0:0 to avoid permission problems
    user: 0:0
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - 18443:18443
      - 18444:18444
      # ZMQ
      - 28332:28332
      - 28333:28333
    volumes:
      - ./volumes/bitcoin:/root/.bitcoin

  arbitrum:
    image: ghcr.io/catalogfi/garden_sol:latest
    container_name: arbitrum
    environment:
      CHAIN_ID: 31338
      LIGHT: "false"
    ports:
      - 8546:8545

  arbitrum-explorer:
    image: otterscan/otterscan:latest
    container_name: arbitrum-explorer
    depends_on:
      - arbitrum
    environment:
      ERIGON_URL: http://localhost:8546
    ports:
      - 5101:80

  relayer:
    image: ghcr.io/catalogfi/relayer:latest
    container_name: relayer
    restart: unless-stopped
    depends_on:
      - garden-evm-watcher
      - matcher
    ports:
      - 4426:4426

  quote:
    image: ghcr.io/catalogfi/quote:latest
    container_name: quote
    restart: unless-stopped
    depends_on:
      - garden-evm-watcher
      - matcher
    ports:
      - 6969:6969

  ethereum:
    image: ghcr.io/catalogfi/garden_sol:latest
    container_name: ethereum
    environment:
      CHAIN_ID: 31337
      LIGHT: "true"
    ports:
      - 8545:8545

  ethereum-explorer:
    image: otterscan/otterscan:latest
    container_name: ethereum-explorer
    depends_on:
      - ethereum
    ports:
      - 5100:80

  # Block explorer server
  electrs:
    image: ghcr.io/vulpemventures/electrs:latest
    container_name: electrs
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - bitcoin:18443
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:30000
      - --electrum-rpc-addr
      - 0.0.0.0:50000
      - --cors
      - "*"
      - --jsonrpc-import
    depends_on:
      - bitcoin
    ports:
      - 50000:50000
      - 30000:30000
    volumes:
      - ./volumes/bitcoin/:/config
    restart: unless-stopped

  # Block explorer frontend
  esplora:
    image: ghcr.io/vulpemventures/esplora:latest
    container_name: esplora
    depends_on:
      - chopsticks
    environment:
      API_URL: http://localhost:3000
    ports:
      - 5050:5000
    restart: unless-stopped

  # Chopsticks
  chopsticks:
    image: ghcr.io/vulpemventures/nigiri-chopsticks:latest
    container_name: chopsticks
    command:
      - --use-faucet
      - --use-mining
      - --use-logger
      - --rpc-addr
      - bitcoin:18443
      - --electrs-addr
      - electrs:30000
      - --addr
      - 0.0.0.0:3000
    depends_on:
      - bitcoin
      - electrs
    ports:
      - 3000:3000
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garden
    ports:
      - 5432:5432
    volumes:
      - ./volumes/orderbook_data:/var/lib/postgresql/data

  bit-indexer:
    image: ghcr.io/catalogfi/bitindexer:latest
    container_name: bit-indexer
    restart: unless-stopped
    depends_on:
      - garden-evm-watcher
      - matcher


  garden-db:
    image: postgres:alpine
    container_name: garden-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garden
    ports:
      - 5433:5432
    volumes:
      - ./volumes/ponder_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./volumes/cobi_data:/data

  solana-validator:
    image: ghcr.io/catalogfi/solana-test-validator:latest 
    container_name : solana-validator
    ports:
      - 8899:8899
      - 8900:8900
    restart: unless-stopped

  solana-watcher:
    image: ghcr.io/catalogfi/solana-watcher:latest
    container_name : solana-watcher
    depends_on:
      - solana-validator
    restart: unless-stopped

  solana-executor:
    image: ghcr.io/catalogfi/solana-executor:latest
    container_name: solana-executor
    depends_on:
      - solana-watcher
    restart: unless-stopped

  solana-relayer:
    image: ghcr.io/catalogfi/solana-relayer:latest
    ports:
      - 5014:5014
    container_name: solana-relayer
    command: ["--use-testkey"]
    depends_on:
      - solana-validator
    restart: unless-stopped

  virtual-balance:
    image: ghcr.io/catalogfi/virtual-balance:latest
    container_name: virtual-balance
    depends_on:
      - ethereum
      - electrs
    restart: unless-stopped

  orderbook:
    image: ghcr.io/catalogfi/orderbook:latest
    container_name: orderbook
    depends_on:
      - ethereum
      - arbitrum
      - chopsticks
      - postgres
    ports:
      - 8080:8080
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cobi:
    image: ghcr.io/catalogfi/cobi:latest
    container_name: cobi
    depends_on:
      - orderbook
      - redis
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # following services will be part of gardenv2 stack
  garden-evm-watcher:
    image: ghcr.io/catalogfi/garden-evm-watcher:latest
    container_name: garden-evm-watcher
    depends_on:
      - ethereum
      - arbitrum
      - chopsticks
      - garden-db
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  matcher:
    image: ghcr.io/catalogfi/matcher:latest
    container_name: matcher
    depends_on:
      - garden-evm-watcher
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  bit-ponder:
    image: ghcr.io/catalogfi/bit-ponder:latest
    container_name: bit-ponder
    depends_on:
      - garden-evm-watcher
      - matcher
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cobiv2:
    image: ghcr.io/catalogfi/cobiv2:latest
    container_name: cobiv2
    depends_on:
      - garden-evm-watcher
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  cosigner:
    image: ghcr.io/catalogfi/cosigner:latest
    container_name: cosigner
    ports:
      - 11818:11818
    restart: unless-stopped

  starknet-devnet:
    image: shardlabs/starknet-devnet-rs:latest
    container_name: starknet-devnet
    command: ["--seed", "1", "--dump-on", "exit", "--dump-path", "/data/dump.json"]
    ports:
      - "8547:5050"
    volumes:
      - ./starknet/dump.json:/data/dump.json
  
  garden-starknet-watcher:
    image: ghcr.io/catalogfi/garden-starknet-watcher:merry
    container_name: starknet-watcher
    depends_on:
      - starknet-devnet
    restart: unless-stopped

  starknet-relayer:
    image: ghcr.io/catalogfi/starknet-relayer:merry
    container_name: starknet-relayer
    depends_on:
      - starknet-devnet
      - garden-db
    ports:
      - "4436:4436"
    restart: unless-stopped

  starknet-executor:
    image: ghcr.io/catalogfi/starknet-executor:merry
    container_name: starknet-executor
    depends_on:
      - starknet-devnet
      - garden-db
    restart: unless-stopped
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - bitcoin
      - arbitrum
      - arbitrum-explorer
      - ethereum
      - ethereum-explorer
      - electrs
      - esplora
      - chopsticks
      - postgres
      - redis
      - orderbook
      - cobi
      - cosigner

networks:
  default:
    name: merry
