orderbook_url = "http://orderbookV2:4455/"

[[chains]]
name = "bitcoin_regtest"
rpc = "http://electrs:30000/"
addresses = ["cobi:bcrt1qgyf47wrtnr9gsr06gn62ft6m4lzylcnllrf9cf"]
chain_type = "btc"
native_token_id = "bitcoin"
decimals = 8

[[chains]]
name = "ethereum_localnet"
rpc = "http://ethereum:8545/"
addresses = [
    "cobi:0x70997970c51812dc3a010c7d01b50e0d17dc79c8",
    "relayer:0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
]
chain_type = "evm"
native_token_id = "ethereum"
decimals = 18

[[chains]]
name = "arbitrum_localnet"
rpc = "http://arbitrum:8545/"
addresses = [
    "cobi:0x70997970c51812dc3a010c7d01b50e0d17dc79c8",
    "relayer:0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "creator:0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
]
chain_type = "evm"
native_token_id = "ethereum"
decimals = 18