# Database configuration
db_url = "postgres://postgres:postgres@garden-db:5432/garden"

# Starknet node configuration
rpc_url = "http://starknet-devnet:5050/rpc"

# Block configuration
start_block = 0
max_block_span = 1000
polling_interval = 100

# Environment configuration
blockchain = "starknet_devnet"

# Worker configuration
worker_count = 1
queue_size = 1000

htlc_contracts = [
    "0x76f1c2d4fe41e381f368130ef47fa9d8791b3badd5b4a844d06154e99ae56c5",
    "0x37b703339cd490399064ec5203301bfe73b57c96007cec23b406ad22bf61045"
]